name: "✨ Feature Request"
description: Suggest a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request\nHave an idea for a new feature? Let us know!\n\n💡 **Before you submit:**\nCheck [GitHub Discussions](../../discussions) to see if this idea has been discussed before."
  - type: input
    id: summary
    attributes:
      label: "Summary"
      placeholder: "Ex: Add a Twitch chat auto-moderation system."
  - type: textarea
    id: problem
    attributes:
      label: "What problem does this solve?"
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
  - type: textarea
    id: extra
    attributes:
      label: "Additional Context"
